/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.security.Key;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author idiotbox
 */
public class mainApplicaton extends javax.swing.JFrame {
    private final JTextField filename = new JTextField(), dir = new JTextField();
    protected String plainFilePath = null;
    protected File plainFile = null;
    private PublicKey publicKeyRSA;
    private PrivateKey privateKeyRSA;
    private SecretKeySpec publicKeyDES;
    private int size;
    private String extension;
    /**
     * Creates new form mainApplicaton
     */
    public mainApplicaton() {
        initComponents();
        this.setLocationRelativeTo(null);
        buttonGroupEncryption();
        buttonGroupOperation();
        radioNonSensitive.setEnabled(false);
        radioSensitive.setEnabled(false);
        radioHashing.setEnabled(false);
        EncryptionRadio.setEnabled(false);
        DecryptionRadio.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        basePanel = new javax.swing.JPanel();
        headPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        operationPanel = new javax.swing.JPanel();
        EncryptionMethodCombo = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();
        lblTimeTaken = new javax.swing.JLabel();
        lblStoredFileLocation = new javax.swing.JLabel();
        lblMethod = new javax.swing.JLabel();
        lblMethod1 = new javax.swing.JLabel();
        EncryptionRadio = new javax.swing.JRadioButton();
        DecryptionRadio = new javax.swing.JRadioButton();
        radioHashing = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        lblFileName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radioNonSensitive = new javax.swing.JRadioButton();
        radioSensitive = new javax.swing.JRadioButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        basePanel.setBackground(java.awt.Color.white);

        headPanel.setBackground(new java.awt.Color(253, 88, 136));

        jLabel1.setFont(new java.awt.Font("Asana Math", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("ENCRYPTION APPLICATION");

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/delete-filled.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headPanelLayout = new javax.swing.GroupLayout(headPanel);
        headPanel.setLayout(headPanelLayout);
        headPanelLayout.setHorizontalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headPanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblClose)
                .addContainerGap())
        );
        headPanelLayout.setVerticalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headPanelLayout.createSequentialGroup()
                .addGroup(headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblClose)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        operationPanel.setBackground(new java.awt.Color(254, 195, 136));

        EncryptionMethodCombo.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 18)); // NOI18N
        EncryptionMethodCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EncryptionMethodComboFocusGained(evt);
            }
        });

        submitButton.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 18)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        lblTimeTaken.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 18)); // NOI18N
        lblTimeTaken.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblStoredFileLocation.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 18)); // NOI18N
        lblStoredFileLocation.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblMethod.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 18)); // NOI18N
        lblMethod.setForeground(java.awt.Color.darkGray);
        lblMethod.setText("Algorithm :");

        lblMethod1.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 18)); // NOI18N
        lblMethod1.setForeground(java.awt.Color.darkGray);
        lblMethod1.setText("Type :");

        EncryptionRadio.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 18)); // NOI18N
        EncryptionRadio.setText("Encryption");

        DecryptionRadio.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 18)); // NOI18N
        DecryptionRadio.setText("Decryption");

        radioHashing.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 18)); // NOI18N
        radioHashing.setText("Hashing");

        javax.swing.GroupLayout operationPanelLayout = new javax.swing.GroupLayout(operationPanel);
        operationPanel.setLayout(operationPanelLayout);
        operationPanelLayout.setHorizontalGroup(
            operationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMethod1)
                .addGap(49, 49, 49)
                .addComponent(radioHashing)
                .addGap(88, 88, 88)
                .addComponent(EncryptionRadio)
                .addGap(48, 48, 48)
                .addComponent(DecryptionRadio)
                .addGap(52, 52, 52))
            .addGroup(operationPanelLayout.createSequentialGroup()
                .addGroup(operationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(operationPanelLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addGroup(operationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTimeTaken, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                            .addComponent(lblStoredFileLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(operationPanelLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(lblMethod)
                        .addGap(18, 18, 18)
                        .addGroup(operationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EncryptionMethodCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        operationPanelLayout.setVerticalGroup(
            operationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(operationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EncryptionRadio)
                    .addComponent(DecryptionRadio)
                    .addComponent(radioHashing)
                    .addComponent(lblMethod1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(operationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EncryptionMethodCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTimeTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblStoredFileLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        operationPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {EncryptionMethodCombo, lblMethod, lblMethod1, lblStoredFileLocation, lblTimeTaken});

        jPanel1.setBackground(new java.awt.Color(251, 168, 144));

        jLabel4.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.darkGray);
        jLabel4.setText("Select File :");

        btnBrowse.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 18)); // NOI18N
        btnBrowse.setText("Browse File...");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        lblFileName.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 18)); // NOI18N
        lblFileName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel4)
                .addGap(42, 42, 42)
                .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBrowse))
                    .addComponent(lblFileName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBrowse, jLabel4, lblFileName});

        jLabel2.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 18)); // NOI18N
        jLabel2.setText("Operation :");

        radioNonSensitive.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 18)); // NOI18N
        radioNonSensitive.setText("NON SENSITIVE");
        radioNonSensitive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNonSensitiveActionPerformed(evt);
            }
        });

        radioSensitive.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 18)); // NOI18N
        radioSensitive.setText("SENSITIVE");
        radioSensitive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSensitiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basePanelLayout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(basePanelLayout);
        basePanelLayout.setHorizontalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(headPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(operationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3))
            .addGroup(basePanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addComponent(radioNonSensitive)
                .addGap(67, 67, 67)
                .addComponent(radioSensitive)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        basePanelLayout.setVerticalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addComponent(headPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(radioNonSensitive)
                    .addComponent(radioSensitive, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        basePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, radioNonSensitive, radioSensitive});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void buttonGroupEncryption(){
        ButtonGroup bg = new ButtonGroup();
        bg.add(EncryptionRadio);
        bg.add(DecryptionRadio);
    }
    private void buttonGroupOperation(){
        ButtonGroup bg = new ButtonGroup();
        bg.add(radioSensitive);
        bg.add(radioNonSensitive);
    }
    
    private void reset(){
        plainFile = null;
        plainFilePath = null;
        lblFileName.setText("");
        radioNonSensitive.setEnabled(false);
        radioSensitive.setEnabled(false);
        radioHashing.setEnabled(false);
        EncryptionRadio.setEnabled(false);
        DecryptionRadio.setEnabled(false);
        radioNonSensitive.setSelected(false);
        radioSensitive.setSelected(false);
        radioHashing.setSelected(false);
        EncryptionRadio.setSelected(false);
        DecryptionRadio.setSelected(false);
        publicKeyRSA = null;
        privateKeyRSA = null;
        size = 0;
        EncryptionMethodCombo.removeAllItems();
     }
    private void fillCombo(int size){
        EncryptionMethodCombo.removeAllItems();
        switch(size){
                case 10:
                    EncryptionMethodCombo.addItem("MD5");
                    break;
                case 11:
                    EncryptionMethodCombo.addItem("SHA1");
                    break;
                case 20:
                    EncryptionMethodCombo.addItem("AES");
                    EncryptionMethodCombo.addItem("BlowFish");
                    break;
                case 21:
                    EncryptionMethodCombo.addItem("DES");
                    EncryptionMethodCombo.addItem("BlowFish");
                    break;
                case 22:
                    EncryptionMethodCombo.addItem("AES");
                    EncryptionMethodCombo.addItem("DES");
                    break;
                case 6:
                    EncryptionMethodCombo.addItem("BlowFish");
                    break;
                case 7:
                    EncryptionMethodCombo.addItem("AES");
                    break;
                default:
        }
                
    }
    
    
    
    private void encType(int ciphermode, Key accessKey, SecretKeySpec secKey){
        JFileChooser c = new JFileChooser();
        int rVal = c.showSaveDialog(this);
        String operation = "";
        operation = EncryptionMethodCombo.getSelectedItem().toString();
        if (rVal == JFileChooser.APPROVE_OPTION) {
        filename.setText(c.getSelectedFile().getName());
        dir.setText(c.getCurrentDirectory().toString());
        plainFilePath = dir.getText()+"/"+filename.getText();
        
        if (plainFilePath != null){
            long startTime; 
            long endTime;   
            double time;   
         
        startTime = System.currentTimeMillis();
	
                if(operation.equalsIgnoreCase("AES")){
                    String key = "This is a secret";
                    Crypto.fileProcessorAES(ciphermode, key, plainFile, new File(plainFilePath));
                }else if(operation.equalsIgnoreCase("DES")){
                    Crypto.fileProcessorDES(ciphermode, secKey, plainFile, new File(plainFilePath));
                }else if(operation.equalsIgnoreCase("SHA1")){
                    Crypto.fileProcessorSHA(plainFile, new File(plainFilePath));
                }else if(operation.equalsIgnoreCase("MD5")){
                    Crypto.fileProcessorMD5(plainFile, new File(plainFilePath));
                }else if(operation.equalsIgnoreCase("BlowFish")){
                    String keyString = "DesireSecretKey";
                    Crypto.fileProcessorBlowFish(ciphermode, keyString, plainFile, new File(plainFilePath));
                }
                            
            endTime = System.currentTimeMillis();
            time = (endTime - startTime) / 1000.0;
            lblTimeTaken.setText("Execution Time : " +Double.toString(time));
            lblStoredFileLocation.setText(plainFilePath);
            JOptionPane.showMessageDialog(this, "File is stored at :"+ plainFilePath);
        }
      }
      if (rVal == JFileChooser.CANCEL_OPTION) {
        filename.setText("You pressed cancel");
        dir.setText("");
        
      }
    }
    
    
    private void encryptionSelection(String ext, int size, int state){
        switch(ext){
                case "jpeg" :
                case "jpg":
                    if(state==1){
                        fillCombo(10);
                    }else if(state ==2){
                        fillCombo(20);
                    }             
                    break;
                case "zip":
                    if(state==1){
                        fillCombo(10);
                    }else if(state ==2){
                        fillCombo(20);
                    }             
                    break;
                case "gif":
                    if(state==1){
                        fillCombo(10);
                    }else if(state ==2){
                        fillCombo(21);
                    }             
                    break;
                case "3gp":
                    if(state==1){
                        fillCombo(10);
                    }else if(state ==2){
                        fillCombo(20);
                    }             
                    break;
                case "png":
                    if(state==1){
                        fillCombo(10);
                    }else if(state ==2){
                        fillCombo(20);
                    }             
                    break;
                case "mp4":
                case "xls":
                case "flv":
                case "mkv":
                case "svg":
                case "pdf":
                default:
        }
                
    }
    
    
    private void radioSelect(){
        int state = -1;
        if(radioNonSensitive.isSelected()){
           state = 1;
           radioHashing.setEnabled(true);
           EncryptionRadio.setSelected(false);
           DecryptionRadio.setSelected(false);
           EncryptionRadio.setEnabled(false);
           DecryptionRadio.setEnabled(false);
        }else if(radioSensitive.isSelected()){
           state = 2;
           radioHashing.setEnabled(false);
           radioHashing.setSelected(false);
           EncryptionRadio.setEnabled(true);
           DecryptionRadio.setEnabled(true);
       }
        encryptionSelection(extension, size,state);
    }
    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        lblTimeTaken.setText("");
        lblStoredFileLocation.setText("");
        extension = null;
        size=0;
        JFileChooser plainFileChooser = new JFileChooser();
        int rVal = plainFileChooser.showSaveDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION) {
            plainFile = plainFileChooser.getSelectedFile();
            extension = FilenameUtils.getExtension(plainFileChooser.getSelectedFile().toString());
            System.out.println(extension);
            size = (int) plainFile.length() / 1024;
            lblFileName.setText(plainFileChooser.getSelectedFile().getName()+"  "+size+ "  KB");
            radioNonSensitive.setEnabled(true);
            radioSensitive.setEnabled(true);
        }
        if (rVal == JFileChooser.CANCEL_OPTION) {
            filename.setText("You pressed cancel");
            dir.setText("");
            extension = null;
            size=0;
            radioNonSensitive.setEnabled(false);
            radioSensitive.setEnabled(false);
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        WindowEvent winClosingEvent = new WindowEvent(SwingUtilities.getWindowAncestor(basePanel), WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void EncryptionMethodComboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EncryptionMethodComboFocusGained
        
    }//GEN-LAST:event_EncryptionMethodComboFocusGained

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try {
            Key k = KeyGenerator.getInstance("DES").generateKey();
            byte [] raw = k.getEncoded();
            publicKeyDES = new SecretKeySpec(raw, "DES");
            
            if(EncryptionRadio.isSelected()){
                if(EncryptionMethodCombo.getSelectedItem().toString().equalsIgnoreCase("DES")){
                    encType(Cipher.ENCRYPT_MODE,null,publicKeyDES);
                    String key64 = Base64.getEncoder().encodeToString(publicKeyDES.getEncoded());
                    JOptionPane.showMessageDialog(null, new JTextArea(key64), "Private Key", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    encType(Cipher.ENCRYPT_MODE, null, null);
                }
            }else{
                if(EncryptionMethodCombo.getSelectedItem().toString().equalsIgnoreCase("DES")){
                    String keyString = JOptionPane.showInputDialog("Enter Private Key");
                    byte[] decodedKey = Base64.getDecoder().decode(keyString);
                    SecretKeySpec key = new SecretKeySpec(decodedKey, 0, decodedKey.length, "DES");
                    encType(Cipher.DECRYPT_MODE,null,key);
                }else{
                    encType(Cipher.DECRYPT_MODE, null, null);
                }
            }
            reset();
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(mainApplicaton.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void radioNonSensitiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNonSensitiveActionPerformed
       radioSelect();
    }//GEN-LAST:event_radioNonSensitiveActionPerformed

    private void radioSensitiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSensitiveActionPerformed
       radioSelect();
    }//GEN-LAST:event_radioSensitiveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainApplicaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainApplicaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainApplicaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainApplicaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainApplicaton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DecryptionRadio;
    private javax.swing.JComboBox<String> EncryptionMethodCombo;
    private javax.swing.JRadioButton EncryptionRadio;
    private javax.swing.JPanel basePanel;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JPanel headPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblFileName;
    private javax.swing.JLabel lblMethod;
    private javax.swing.JLabel lblMethod1;
    private javax.swing.JLabel lblStoredFileLocation;
    private javax.swing.JLabel lblTimeTaken;
    private javax.swing.JPanel operationPanel;
    private javax.swing.JRadioButton radioHashing;
    private javax.swing.JRadioButton radioNonSensitive;
    private javax.swing.JRadioButton radioSensitive;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
